### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by gabinfinity** [lamhoang1256/netfilm#10]
![image](https://user-images.githubusercontent.com/59806981/214783103-1dbaa6c9-350d-4fd8-b6ef-9996e90c5eab.png)
![image](https://user-images.githubusercontent.com/59806981/214783127-e26c3c4a-56a6-441d-b011-3e483b5a3687.png)

When I log in, it says it worked but it gets stuck on the login screen

**Comment by gabinfinity** [comment]
I fixed it :)

**Comment by Danny-Nunez** [comment]
i have the same error how di you fix it

**Comment by Danny-Nunez** [comment]
> I fixed it :)

how did you fix it
