### ISSUE TITLE
Integrate netfilm to Sora

### ISSUE THREAD

**Issue by gabinfinity** [lamhoang1256/netfilm#11]
Hi dude, can you help me? im trying to integrate your api to SORA but its difficult. https://github.com/gabinfinity/Sora

**Comment by lamhoang1256** [comment]
@gabinfinity Sorry bro but I tried reading the Sora project code, it's too big and a bit confusing

**Comment by lamhoang1256** [comment]
I think you should try creating an issue with the error label so the author can help
