### ISSUE TITLE
add pwa support

### ISSUE THREAD

**Issue by bachig26** [lamhoang1256/netfilm#13]
add the pwa support to the site to use it as a web app in the mobile.

**Comment by lamhoang1256** [comment]
@bachig26 Hey bro, I use 1 api from Loklok and Loklok's main revenue is mobile app so the policies for using api on pwa, mobile are very strict. So I'm afraid to build your feature, hope you understand for me

**Comment by bachig26** [comment]
@lamhoang1256 is there app for iOS to use loklok? possibly an ipa to sideload?

**Comment by lamhoang1256** [comment]
@bachig26 I only use Android, never used iOS, so I'm not sure. I tried to use mobile emulator on pc to find api and test responsive from loklok app but got error and just showing blank page

**Comment by lamhoang1256** [comment]
I think when you want to use api on mobile you have to have a secret key from Loklok to be able to call them
