### ISSUE TITLE
Job

### ISSUE THREAD

**Issue by Convitt** [lamhoang1256/netfilm#15]
Great work on Netfilm, congrats! Are you available for a freelance job? I need to add the imdb api in a player. It's full frontend

**Comment by lamhoang1256** [comment]
@Convitt Can you send me your job information so I can refer? Your mail: **lamhoang1256@gmail.com**

**Comment by Convitt** [comment]
Done :)

**Comment by lamhoang1256** [comment]
@Convitt Hey bro i checked my mail and saw the opensubtitles link and you want to add them to your imdb project right?

**Comment by lamhoang1256** [comment]
@Convitt I see imdb only provides short video trailers

**Comment by Convitt** [comment]
Nop. I have a project to watch movies and series online. Like yours. But it has no subtitles. I need to integrate the opensubtitles api for people to use subtitles to watch.

**Comment by Convitt** [comment]
If the api I sent you doesn't work, you can use the opensubtitles api. https://opensubtitles.stoplight.io/docs/opensubtitles-api/e3750fd63a100-getting-started

**Comment by lamhoang1256** [comment]
@Convitt Ok bro, You can send the source code or movie source to me for try processing. If you want private you can send it to my gmail

**Comment by lamhoang1256** [comment]
I need to check the subtitles and the movie source can interact with each other

**Comment by Convitt** [comment]
I sent the project link on email bro

**Comment by Convitt** [comment]
Just run 

yarn install
yarn start

or yarn build to build

**Comment by lamhoang1256** [comment]
@Convitt ok bro, I got the source code already. I'm working on it, I'll message you later

**Comment by Convitt** [comment]
perfect bro, im waiting for you

**Comment by Convitt** [comment]
any update bro?

**Comment by lamhoang1256** [comment]
@Convitt I found the opensubtitles link you gave me and if you want to use it, every time you use subtitile, You have to download the subtitle you want to watch and then import it into the player.

**Comment by lamhoang1256** [comment]
Example the video you want to watch mr bean, you must download that subtitle mr bean to your device or phone, and then after downloading, you can get the downloaded subtitles and use

**Comment by lamhoang1256** [comment]
@Convitt I'm looking for a way to use live subtitles without downloading, but haven't found one yet. Do you want to use the above method or find another source of subtitles?

**Comment by lamhoang1256** [comment]
@Convitt Currently I have this option, you can see

**Comment by lamhoang1256** [comment]
When the user select the movie, I will use opensubtitles to suggest the subtitles you need to download

**Comment by lamhoang1256** [comment]
And when the user select the subtitle with the appropriate language and downloads it, I will create a button on the web for the user to select the subtitle that has just been downloaded and then use

**Comment by lamhoang1256** [comment]
Do you think this is ok?

**Comment by Convitt** [comment]
what do you think?

**Comment by Convitt** [comment]
You can use this example repository. It uses the official opensubtitles api (https://github.com/Khanhtran47/Sora)

**Comment by lamhoang1256** [comment]
@Convitt ok bro , I will research new opensubtitles link

**Comment by Convitt** [comment]
> And when the user select the subtitle with the appropriate language and downloads it, I will create a button on the web for the user to select the subtitle that has just been downloaded and then use

If it doesn't work otherwise, it might be like this.

**Comment by Convitt** [comment]
there is bazarr https://www.bazarr.media/#features, but its not a api, idk if his can help you

**Comment by Convitt** [comment]
> And when the user select the subtitle with the appropriate language and downloads it, I will create a button on the web for the user to select the subtitle that has just been downloaded and then use

Let's do this way. Is it possible to put the Portuguese subtitles highlighted to download?

**Comment by lamhoang1256** [comment]
@Convitt I will research new opensubtitles to use it directly, if not I will follow the above method

**Comment by Convitt** [comment]
okay bro

**Comment by lamhoang1256** [comment]
@Convitt 
Hey bro I'm still researching to use live subtitles, but I've tried uploading subtitles and there's still subtitle suggestion.
Here is a simple demo, do you think it's ok?

https://user-images.githubusercontent.com/61537853/216219236-f3bc719d-e360-4ec8-b117-45160efc5e99.mp4

**Comment by Convitt** [comment]
its perfect bro. But where is the suggestion subs?

**Comment by lamhoang1256** [comment]
@Convitt  Suggestions, just id imdb, my web will go to the subtitles suggestion page on opensubtitles . But there is a problem that opensubtitles only allows to download 10 subtitles/day and if logged in it is 20. I think it's a little, what do you think?

![image](https://user-images.githubusercontent.com/61537853/216229365-8030dfd8-5501-4b64-9309-0fb9c5a6da5e.png)

**Comment by gabinfinity** [comment]
Its 10 per user

**Comment by gabinfinity** [comment]
The unofficial api can help us

**Comment by lamhoang1256** [comment]
@Convitt Official opensubtitles supports finding movies with imdb, but I don't know the unofficial version supports it yet

Example: imdb id: **tt10752004**
https://www.imdb.com/title/tt10752004
https://www.opensubtitles.com/title/tt10752004

**Comment by lamhoang1256** [comment]
@Convitt I found flixhq web in your source. This website supports subtitles in many languages, why don't you use them?

Example: https://flixhq.ru/movie/puss-in-boots-the-last-wish-30852/1-full

**Comment by gabinfinity** [comment]
Is it possible use just subtitles ftom flixhq? I need all providers working. SuperStream hss subtitles too

**Comment by lamhoang1256** [comment]
@gabinfinity Do you have a doc link or information about SuperStream. I don't see superstream supporting subtitles?

**Comment by lamhoang1256** [comment]
@gabinfinity I think the use of many film providers a project has its good and bad

- Good: you will have more variety, more movies, more video quality, more subtitles,...
- Bad: you will be very difficult to manage, connect the subtitles with each different providers together, and will be more laggy due to needing more resources

**Comment by gabinfinity** [comment]
Maybe suggesting subs and uploading them is the best way

**Comment by gabinfinity** [comment]
What do you think bro

**Comment by Convitt** [comment]
That's great, suggesting the subtitle and being able to upload. Is it possible to put the upload button at the bottom of the player? In this way.
![image](https://user-images.githubusercontent.com/122373050/216307581-a72871a3-29f9-4b84-9b63-68a46cd825e2.png)

**Comment by Convitt** [comment]
lets do it?

**Comment by Convitt** [comment]
you r awesome, do you have discord?

**Comment by Convitt** [comment]
I had an idea, see if it's possible. Instead of the subtitle being downloaded to the user's device, it is downloaded to our server. When the user clicks on the selected subtitle, the server downloads the subtitle from Opensubtitle and loads the subtitle in the player. To identify the subtitle directory, we can save using the imdb ID.

**Comment by lamhoang1256** [comment]
@Convitt If you use this idea, I think you will get the opensubtitles limitation error because you are the only one to download.

**Comment by lamhoang1256** [comment]
@Convitt Temporarily you can check the source code I sent via gmail. If you need to fix anything, just message me

**Comment by lamhoang1256** [comment]
@Convitt I'm still researching another way, but you can try the idea of the source code I sent you, is it ok?

**Comment by gabinfinity** [comment]
> @Convitt If you use this idea, I think you will get the opensubtitles limitation error because you are the only one to download.

Maybe bro, but i think i gonna buy the premium api, its 50 bucks per month, so its wont get limitations

**Comment by lamhoang1256** [comment]
@gabinfinity This is a good idea. If I use this idea, I need time to research and I also don't like having to download subtitle every time I watch movie.

**Comment by Convitt** [comment]
i tested the source dode and works fine, awesome, im reasearching something too

**Comment by Convitt** [comment]
> I had an idea, see if it's possible. Instead of the subtitle being downloaded to the user's device, it is downloaded to our server. When the user clicks on the selected subtitle, the server downloads the subtitle from Opensubtitle and loads the subtitle in the player. To identify the subtitle directory, we can save using the imdb ID.

This solution is possible? I can buy the premium API

**Comment by lamhoang1256** [comment]
@Convitt I need about half a day or 1 day to research this idea, but do you need it urgently?

**Comment by Convitt** [comment]
a little bit. im searching too. I found this https://github.com/Ram-saddist/auto-subtitles
its automatic. Maybe use it with a translator can be good, idk

**Comment by Convitt** [comment]
![image](https://user-images.githubusercontent.com/122373050/216511217-6563f3a8-d767-4b6b-aad0-927f19e7a323.png)
a report, the option Opensubtitles and upload doesnt show on some old movies, but there is subtitles https://www.opensubtitles.com/pt-PT/movies/1999-don-t-look-under-the-bed

**Comment by Convitt** [comment]
https://github.com/GabrielCote1999/SubtitleAdder

**Comment by lamhoang1256** [comment]
@Convitt I'm working on how to get subtitles directly from opensubtitles but maybe rebuild new source code because the code you gave me is not suitable

**Comment by Convitt** [comment]
directly from opensubs is very hard

**Comment by lamhoang1256** [comment]
@Convitt I'm researching it might be possible, but can't reuse your old source code

**Comment by lamhoang1256** [comment]
If you can use it directly, do you have to remove the old code?

**Comment by Convitt** [comment]
> If you can use it directly, do you have to remove the old code?

I didn't understand

**Comment by Convitt** [comment]
If you need to change the source code, no problem

**Comment by lamhoang1256** [comment]
@Convitt In order to stream opensubtitles directly I need to code a backend and only need a stable source of movies without errors to get subtitles.

**Comment by lamhoang1256** [comment]
@Convitt Your source code currently use many movie provider but sometimes it is unstable, and it is too complicated to edit. I think it's code by many people so it's a bit difficult to read , so i want to create a new one

**Comment by Convitt** [comment]
No problem. I had no problems with providers. For loklok to work you need to have the code hosted in Australia, if not the code is unstable

**Comment by lamhoang1256** [comment]
@Convitt I will consider and find the best provider to use

**Comment by Convitt** [comment]
The best providers is Loklok, FlixHQ and SuperStream

**Comment by lamhoang1256** [comment]
@Convitt Ok bro i will research but the feature get directly subtitles is difficult, it will take a while bro

**Comment by Convitt** [comment]
I made a google cloud vm hosted at Australia to test http://35.244.114.107/#/search/movie

**Comment by Convitt** [comment]
![image](https://user-images.githubusercontent.com/122373050/216521061-88fe29a2-ac8d-4cb8-8df6-904b89def28d.png)
I really think there is a problem with the provider search. Drag Race season 15 is available on Loklok, but when searching, nothing is found.

**Comment by lamhoang1256** [comment]
@Convitt I will check the provider of the movie, and the source code I send you when you click open subtitles it will switch to the page that suggests what language for you? Does it suggest you portuguese or english?

![image](https://user-images.githubusercontent.com/61537853/216536809-e43eaf61-40f9-4a71-a527-7fc0433d0e44.png)

**Comment by Convitt** [comment]
Portuguese

**Comment by Convitt** [comment]
everything is working fine, but like i said "I really think there is a problem with the provider search. Drag Race season 15 is available on FlixHQ, but when searching, nothing is found."

**Comment by lamhoang1256** [comment]
@Convitt I read your source and found that when searching movie it will call an api Justwatch. Justwatch will get the list of movies you are looking for and when you click select one movie, justwatch will search for streaming sources from flixhq

**Comment by lamhoang1256** [comment]
@Convitt So even though flixhq has movie X but justwatch doesn't have movie X => the website will return no movie X. Movie provider depends on Justwatch

**Comment by Convitt** [comment]
but there is season 15 https://www.justwatch.com/br/serie/rupauls-drag-race/temporada-15

some users report this error

**Comment by lamhoang1256** [comment]
@Convitt I think your source code is a bit buggy, currently I plan to use 2 api: justwatch to search movie and hqflix to get streaming source and opensubtitles

**Comment by Convitt** [comment]
flixhq is very good, maybe use flixhq and loklok can be the best option

**Comment by Convitt** [comment]
bro, is it possible to add your api to Sora? (https://github.com/Khanhtran47/Sora) Sora works fine with opensubtitles

**Comment by lamhoang1256** [comment]
@Convitt I found Sora's source to find a very complicated movie:

```export const getSubtitlesSearch = async (
  id?: number,
  imdb_id?: number,
  tmdb_id?: number,
  parent_feature_id?: number,
  parent_imdb_id?: number,
  parent_tmdb_id?: number,
  query?: string,
  ai_translated?: 'exclude' | 'include',
  episode_number?: number,
  foreign_parts_only?: 'exclude' | 'include' | 'only',
  hearing_impaired?: 'exclude' | 'include' | 'only',
  languages?: string,
  machine_translated?: 'exclude' | 'include',
  moviehash?: string,
  moviehash_match?: string,
  order_by?: string,
  order_direction?: 'asc' | 'desc',
  page?: number,
  season_number?: number,
  trusted_sources?: 'include' | 'only',
  type?: 'movie' | 'episode' | 'all',
  user_id?: number,
  year?: number,
): Promise<ISubtitlesSearch | undefined> => {
```

**Comment by lamhoang1256** [comment]
@Convitt instead  create a backend that simply passes imdbId and you can get the subtitle list right away

![image](https://user-images.githubusercontent.com/61537853/216621986-542a6001-ab7b-48e3-bb8a-b662614c96e1.png)

**Comment by lamhoang1256** [comment]
@Convitt Do you feel ok?

**Comment by Convitt** [comment]
wooow, awesomee!!!

**Comment by Convitt** [comment]
is it will display live subtitles or download subs withou a redirect?

**Comment by lamhoang1256** [comment]
Not need download subtitles

**Comment by Convitt** [comment]
awsome bro, can't wait to see it working 😀

**Comment by Convitt** [comment]
im very excited

**Comment by lamhoang1256** [comment]
@Convitt 😀, I have to go to bed at night in my country, so I will update you on the project after half a day.

**Comment by Convitt** [comment]
ok, good night

**Comment by Convitt** [comment]
I'm awake bro. If you need anything, let me know

**Comment by lamhoang1256** [comment]
@Convitt hey bro you can download subtitle https://www.opensubtitles.org/en/subtitleserve/sub/9328441 and check it. 
I don't know if it conflicts with my pc's language. Did you check if it has black dot error?

![image](https://user-images.githubusercontent.com/61537853/216748731-121ff0ee-08ac-4d8d-bce7-6ee9c74f443a.png)

**Comment by Convitt** [comment]
i think is your O.S language, portuguese has many differect characteres

**Comment by Convitt** [comment]
![image](https://user-images.githubusercontent.com/122373050/216748975-f228b8be-717d-4498-9b01-5aca5d515ab0.png)

**Comment by lamhoang1256** [comment]
@Convitt Bro, I got the subtitles directly through imdbId

![image](https://user-images.githubusercontent.com/61537853/216751248-71757366-7ce6-4e34-8047-cfe4d09a1b45.png)

**Comment by lamhoang1256** [comment]
There is still the problem of 10 downloads limit of Opensubtitles and downloading by episode count is fine

**Comment by lamhoang1256** [comment]
I think this feature still needs to be optimized but glad it is possible

**Comment by Convitt** [comment]
you r very impressive bro, i will buy i think premium api

**Comment by Convitt** [comment]
probably with a premium key we can icrease the limits

**Comment by Convitt** [comment]
is it working with the player?

**Comment by lamhoang1256** [comment]
@Convitt It works well on video player

**Comment by Convitt** [comment]
im excited to test

**Comment by lamhoang1256** [comment]
@Convitt Now I try fake ip address when i get subtitles from opensubtitles i feel fine no limit 10

**Comment by lamhoang1256** [comment]
@Convitt I just tried to create a discord account and I need to make friends or do something to chat with you more convenient?

**Comment by Convitt** [comment]
Try to send me a friend request, this is my user account: G+#7009

**Comment by gabinfinity** [comment]
Hey bro, i has been hacked, can you send me another friend request to my new discord account? Im trying to recovery the another.  

Account: someusername#2836
