### ISSUE TITLE
🐛: Trùng phụ đề

### ISSUE THREAD

**Issue by shenlong616** [lamhoang1256/netfilm#16]
Em chào anh ạ!

### Mô tả lỗi:

- Khi em tua phim và đồng thời "**_chuyển các tập phim_**" với nhau liên tục (>= 2 lần) thì xảy việc "phụ đề cũ chèn vào phụ đề mới" hoặc "phụ đề mới ko đc tải"!?

#### Tập 1:
![image](https://user-images.githubusercontent.com/15698245/216594990-825995a5-c61e-40c6-8429-65b3e1c8c221.png)

#### Tập 2:
![image](https://user-images.githubusercontent.com/15698245/216595105-850f2ac3-0bcc-4b5a-a564-d3c89c06ec2c.png)

### Góc `dev`:

1. `{props: { data }}`
https://github.com/lamhoang1256/netfilm/blob/8063971674dcf21ddcb1254b0cc14d9dc7fc12f3/src/pages/watch/%5Bcategory%5D/%5Bid%5D/index.tsx#L19
2. `<MediaPlayer subtitles/>`
https://github.com/lamhoang1256/netfilm/blob/8063971674dcf21ddcb1254b0cc14d9dc7fc12f3/src/modules/WatchPage/WatchPage.tsx#L103-L108
3. `const { data } = props.pageProps`
![image](https://user-images.githubusercontent.com/15698245/216599166-5f43c845-fbc5-4054-a3b5-c330ead72012.png)

- Em kt `dev mục 3` thì `data.subtitles` ko đổi khi chuyển tập

**Comment by lamhoang1256** [comment]
@shenlong616 Cảm ơn bác nhé e vừa kiểm tra thì thấy có lỗi thật nhưng vẫn chưa biết nó bắt nguồn từ đâu. Hiện tại e đoán có thể do ```data.subtitles``` không đổi như bác nói hoặc là do cái thư viện react-tuby player bị lỗi. E sẽ kiểm tra và ráng fix sớm thôi 😊

**Comment by shenlong616** [comment]
@lamhoang1256 ok ạ!
