### ISSUE TITLE
[Bug] 404 not found for all show in netfilm

### ISSUE THREAD

**Issue by RainbowSaga** [lamhoang1256/netfilm#17]
![Screenshot 2023-01-30 113146](https://user-images.githubusercontent.com/117321707/216958902-f277f6a9-4bd3-4d9d-9813-885205cc8298.png)

pls fix when you have time 🙏 @lamhoang1256

**Comment by Adhaaz** [comment]
There is an error in the API details section, Maybe it's being fixed by @lamhoang1256

**Comment by Adhaaz** [comment]
![IMG_20230206_205240](https://user-images.githubusercontent.com/75169859/216989248-d3b10f05-af29-4c74-a6a9-c4e60a5a24f4.jpg)

Sir @lamhoang1256 , the API encountered an Error, in the Movie and Episode Details section. Can u fix it? ☺️🙏

**Comment by lamhoang1256** [comment]
@RainbowSaga @Adhaaz I appreciate it bro, but I don't have time yet, I'll fix it next week

**Comment by Adhaaz** [comment]
> @RainbowSaga @Adhaaz I appreciate it bro, but I don't have time yet, I'll fix it next week

Don't take long, sir 🥹
My website visitors are complaining all about it, I don't know what to do 🥹🙏

**Comment by lamhoang1256** [comment]
@RainbowSaga @Adhaaz I already fixed it, just a few changes of Loklok really took me a lot of time 😨

**Comment by RainbowSaga** [comment]
> @RainbowSaga @Adhaaz I already fixed it, just a few changes of Loklok really took me a lot of time 😨

thank you so much sir... @lamhoang1256 
just of curiosity may i know how you interfere with the api?
maybe someday i can fix that from my own 😄

**Comment by lamhoang1256** [comment]
@RainbowSaga This is also very difficult to explain bro, I checked for half a day in many places of Loklok so I think it is not easy to find exactly where the error 😅
