### ISSUE TITLE
no covers showing

### ISSUE THREAD

**Issue by Danny-Nunez** [lamhoang1256/netfilm#18]
After clicking on a movie i get 404 not found . I have set up the server and ariea to austrailia and reason why this is happening

<img width="1291" alt="Screen Shot 2023-02-09 at 10 25 39 PM" src="https://user-images.githubusercontent.com/114783191/217992989-76eea978-a557-41a7-b8dc-40de73d5470a.png">

**Comment by lamhoang1256** [comment]
@Danny-Nunez Some movie error or all movie in website error? Sometimes Loklok api also have some movie error

**Comment by Danny-Nunez** [comment]
Thank you for the quick reply. Everything works now it was the Asia server issue. lok lok was blocking the movies from showing. The only issue I’m having now is the login. It will say successfully logged in but doesn’t go to the next page and if I go back to the home page it will still say sign inSent from my iPhoneOn Feb 10, 2023, at 4:18 AM, Nguyen Hoang Lam ***@***.***> wrote:﻿
@Danny-Nunez Some movie error or all movie in website error? Sometimes Loklok api also have some movie error

**Comment by lamhoang1256** [comment]
@Danny-Nunez Please check email

**Comment by Danny-Nunez** [comment]
All good now ty
