### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Adhaaz** [lamhoang1256/netfilm#19]
![IMG_20230213_112407](https://user-images.githubusercontent.com/75169859/218370168-0e8e3ef8-0685-461d-8ee8-0717baf517af.jpg)

Sir @lamhoang1256 , the bug when streaming a movie or series happens again. Only shows loading without any video playing ☺️

**Comment by lamhoang1256** [comment]
@Adhaaz I will fix it soon

**Comment by Adhaaz** [comment]
> @Adhaaz I will fix it soon

Okay sir 👌

**Comment by lamhoang1256** [comment]
@Adhaaz Done fix, please check

**Comment by lamhoang1256** [comment]
@Adhaaz Check **2** new commit

**Comment by Adhaaz** [comment]
> @Adhaaz Done fix, please check

Okay sir, I'll check ☺️

**Comment by Adhaaz** [comment]
> @Adhaaz Check **2** new commit of me

![IMG_20230215_161138](https://user-images.githubusercontent.com/75169859/218984363-ffd6d484-8495-43cc-a6f4-65ecacff78da.jpg)

Sir @lamhoang1256  , The Bug when streaming a movie or series happens again. Only shows loading without any video playing 🥹
