### ISSUE TITLE
Api subtitle https://convert-srt-to-vtt.vercel.app is crashed

### ISSUE THREAD

**Issue by lamhoang1256** [lamhoang1256/netfilm#2]
@Adhaaz, Hey bro at Netfilm project I use api https://convert-srt-to-vtt.vercel.app to convert subtitle but probably many projects Youme, Netfilm clone call this api so vercel warning limited

**Comment by lamhoang1256** [comment]
I think this api will crash so please check https://github.com/hoanglam1309a/SRTtoVTT to create new a vercel api covert subtitle to keep your movie app working

**Comment by lamhoang1256** [comment]
After creating a new vercel api go to your-daflixx/configs/path.api.ts edit srtToVtt to your new link vercel subtitle  Example:https://github.com/lamhoang1256/netfilm/blob/main/configs/path.api.ts

**Comment by Adhaaz** [comment]
Ok sir, Thank you for the information ☺️

**Comment by Adhaaz** [comment]
![IMG_20221127_125509](https://user-images.githubusercontent.com/75169859/204121462-42e83ddd-0087-4956-9e6e-ab3bd351a9ee.jpg)
@lamhoang1256 sSir, why are the subtitles still not showing up? I've added the subtitle api, but it still doesn't appear. Is there something wrong I'm doing?

**Comment by lamhoang1256** [comment]
Please try again with "https://srt2vtt.vercel.app/?url="

**Comment by lamhoang1256** [comment]
You missing /?url=

**Comment by Adhaaz** [comment]
Okay, I will try

**Comment by lamhoang1256** [comment]
Ok let me know if it works

**Comment by Adhaaz** [comment]
Work sir 👌

**Comment by Adhaaz** [comment]
Sir, can you add Watch Together like in the Loklok Application?

**Comment by lamhoang1256** [comment]
I think it is possible but I need time to research

**Comment by lamhoang1256** [comment]
I will tag you when I finish it

**Comment by Adhaaz** [comment]
Wow, that's really cool, sir, thank you 🙏☺️

**Comment by lamhoang1256** [comment]
@Adhaaz Hey bro, I has been trying to research and try to do watch together but I realize that it takes a lot of time to optimize but i don't have much free time

**Comment by lamhoang1256** [comment]
Sorry i think i won't do this feature

**Comment by lamhoang1256** [comment]
But I spent some time and found a Loklok movie project that has the same feature as you requested. You can check here https://github.com/vucuong1820/vmc-social/blob/master/src/pages/WatchTogether.jsx

**Comment by lamhoang1256** [comment]
Hope you can get ideas from it

**Comment by Adhaaz** [comment]
> @Adhaaz Hey bro, I has been trying to research and try to do watch together but I realize that it takes a lot of time to optimize but i don't have much free time

Okay sir, it's okay, sorry to bother you 🙏
