### ISSUE TITLE
Arabic Subtitles

### ISSUE THREAD

**Issue by euijoonyeo** [lamhoang1256/netfilm#23]
Hello I want to help you with Arabic subtitle since the Auto Sub is not 100% perfect. thank you ♡

**Comment by lamhoang1256** [comment]
@euijoonyeo I thank you very much for liking the project, but this project is only for learning, research purposes and I don't have too much time to expand it. Maybe I will need your help at some point but not now. Thank you very much

**Comment by euijoonyeo** [comment]
contact me whenever you need me ♡
