### ISSUE TITLE
Explore and Search

### ISSUE THREAD

**Issue by kunal1234523** [lamhoang1256/netfilm#28]
Please fix the Explore and Search feature they are are not working

**Comment by lamhoang1256** [comment]
@kunal1234523 I see those 2 features still working properly. What error do you have, can you take a picture or describe the bug?

**Comment by gusfing** [comment]
can you tell me how to deploy to vercel im trying but the deployment keeps getting failed

**Comment by kunal1234523** [comment]
@lamhoang1256
![image](https://user-images.githubusercontent.com/46216540/233258299-aafba7b0-fc19-4197-929d-56914078e8ca.png)
![2023-04-20_09-58](https://user-images.githubusercontent.com/46216540/233258540-39bca8e9-a489-4bfb-b6fc-0d387e4cb646.png)

**Comment by lamhoang1256** [comment]
@kunal1234523 Please try using website with Chrome. I think api not support Opera browse
