### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by Adhaaz** [lamhoang1256/netfilm#3]
Sir, why does it take so long to load when playing a video, is there a problem with the Loklok API?

**Comment by lamhoang1256** [comment]
![image](https://user-images.githubusercontent.com/61537853/206712530-e232560a-95f3-483d-ad11-18251129a1cd.png)

**Comment by lamhoang1256** [comment]
Sometimes, Loklok api will block resource usage of other websites than loklok.com

**Comment by lamhoang1256** [comment]
I'm still fixing it but it's a bit difficult because I can't directly interfere with the Loklok api

**Comment by Adhaaz** [comment]
Okay sir, Thanks for u information 👌☺️

**Comment by lamhoang1256** [comment]
@Adhaaz Hey bro, sorry for taking so long to check for errors, today i found a way to fix them. It's pretty simple

**Comment by lamhoang1256** [comment]
Go rootProject -> configs -> axiosLoklok.ts
**Change code**  deviceid: Math.random().toString(36).slice(-8)  **to** deviceid: "d274b09a57e629a2"

**Comment by lamhoang1256** [comment]
Hope it helps you and sorry for the long wait 😅

**Comment by Adhaaz** [comment]
Ok sir, I'll try 😀

**Comment by Adhaaz** [comment]
It worked, sir, but some movies and series still have delays, but at least it reduces the problem a bit, Sir
Good job, sir👌😀

**Comment by lamhoang1256** [comment]
@Adhaaz  if you have a phone then try to find a way to get the deviceid of that device and then use

**Comment by lamhoang1256** [comment]
what i sent you is deviceid not real , just for testing, so I think it will be limitations

**Comment by Adhaaz** [comment]
Yeah sir, maybe I'll try using my device id later..

**Comment by hexated** [comment]
@lamhoang1256 first great job with this projects..

Sorry but does the issue got fixed ?
Cause i'm still stuck with loading

https://user-images.githubusercontent.com/37908684/210657676-caadc612-5da6-458c-97b4-135ee94d09d5.mp4

**Comment by lamhoang1256** [comment]
@hexated Thanks bro i think this Loklok api for mobile will recognize phone with deviceid. In case i am using for web so am using 1 fixed deviceid for every api call so maybe its not valid

**Comment by lamhoang1256** [comment]
I will try to fix it soon

**Comment by lamhoang1256** [comment]
@Adhaaz Hey bro, I think this can fix about 90% of video errors you can follow
Please copy all code and paste in **axiosLoklok.ts**

`import axios from "axios";

const randomDeviceId = () => {
  const hexCharacters = "0123456789abcdef";
  let deviceid = "";
  for (let i = 0; i < 16; ++i) {
    deviceid += hexCharacters.charAt(Math.floor(Math.random() * 16));
  }
  return deviceid;
};

const axiosLoklok = axios.create({
  baseURL: process.env.NEXT_PUBLIC_BASE_URL_API,
  headers: {
    lang: "en",
    versioncode: "11",
    clienttype: "ios_jike_default",
    deviceid: randomDeviceId()
  }
});

axiosLoklok.interceptors.response.use(
  async (response) => {
    if (response && response.data) return response.data;
    return response;
  },
  async (error) => {
    const { response } = error;
    const errorResult = { ...response.data, status: response.status };
    return Promise.reject(errorResult);
  }
);

export default axiosLoklok;
`

**Comment by lamhoang1256** [comment]
@hexated You can test it i think most videos will work fine. Please let me know if there is any error thanks bro

**Comment by Adhaaz** [comment]
> @Adhaaz Hey bro, I think this can fix about 90% of video errors you can follow Please copy all code and paste in **axiosLoklok.ts**
> 
> ```
> import axios from "axios";
> 
> const randomDeviceId = () => {
>   const hexCharacters = "0123456789abcdef";
>   let deviceid = "";
>   for (let i = 0; i < 16; ++i) {
>     deviceid += hexCharacters.charAt(Math.floor(Math.random() * 16));
>   }
>   return deviceid;
> };
> 
> const axiosLoklok = axios.create({
>   baseURL: process.env.NEXT_PUBLIC_BASE_URL_API,
>   headers: {
>     lang: "en",
>     versioncode: "11",
>     clienttype: "ios_jike_default",
>     deviceid: randomDeviceId()
>   }
> });
> 
> axiosLoklok.interceptors.response.use(
>   async (response) => {
>     if (response && response.data) return response.data;
>     return response;
>   },
>   async (error) => {
>     const { response } = error;
>     const errorResult = { ...response.data, status: response.status };
>     return Promise.reject(errorResult);
>   }
> );
> 
> export default axiosLoklok;
> ```



> @Adhaaz Hey bro, I think this can fix about 90% of video errors you can follow Please copy all code and paste in **axiosLoklok.ts**
> 
> ```
> import axios from "axios";
> 
> const randomDeviceId = () => {
>   const hexCharacters = "0123456789abcdef";
>   let deviceid = "";
>   for (let i = 0; i < 16; ++i) {
>     deviceid += hexCharacters.charAt(Math.floor(Math.random() * 16));
>   }
>   return deviceid;
> };
> 
> const axiosLoklok = axios.create({
>   baseURL: process.env.NEXT_PUBLIC_BASE_URL_API,
>   headers: {
>     lang: "en",
>     versioncode: "11",
>     clienttype: "ios_jike_default",
>     deviceid: randomDeviceId()
>   }
> });
> 
> axiosLoklok.interceptors.response.use(
>   async (response) => {
>     if (response && response.data) return response.data;
>     return response;
>   },
>   async (error) => {
>     const { response } = error;
>     const errorResult = { ...response.data, status: response.status };
>     return Promise.reject(errorResult);
>   }
> );
> 
> export default axiosLoklok;
> ```

Okay sir, I'll try 😀👌

**Comment by hexated** [comment]
> @hexated You can test it i think most videos will work fine. Please let me know if there is any error thanks bro 😊

I tested and most of the time video work, around 80-90 % work. And some video still doesn't work until i restart the website and try it again..

It Will be nice if video work 100% :pray:
