### ISSUE TITLE
hlsConfig settings

### ISSUE THREAD

**Issue by streamamos** [lamhoang1256/netfilm#32]
Hello, i just found your website and saw that your player is very responsive. Which hlsConfig settings do you use? or how did you made it so it doesn't have any lag or buffering problems? Thanks.

**Comment by lamhoang1256** [comment]
@streamamos Actually, my hlsConfig is quite simple, it's just like the image. And for the player to be smooth, it depends on many factors:
- Good stream m3u8
- Good network
- Good source code player: My player is built from reactjs referencing from [netplayer](https://www.npmjs.com/package/netplayer), [react-tuby](https://react-tuby.vercel.app) and I spend a lot of time optimizing again (delete unnecessary source code, split state, add cache state, ...)
- Some techniques optimizing can be referencing from reactjs: useMemo, useCallback, [million](https://million.dev)

![hls-config](https://github.com/lamhoang1256/netfilm/assets/61537853/05ddbd46-2963-4be3-8b93-0297849894cb)
