### ISSUE TITLE
Not found  sources NetFilm  it does not work

### ISSUE THREAD

**Issue by Doctor2023** [lamhoang1256/netfilm#34]
![IMG_0694](https://github.com/lamhoang1256/netfilm/assets/129991276/0a208eb3-3c1e-4c21-885d-04701d5b9441)

I can not see in some movies and series I get Not found sources
on the NetFilm page source superstream
some sources do not work in movies and series page NetFilm

**Comment by lamhoang1256** [comment]
Yes, Netfilm will have some movies and series that can't be scrape so display Not found sources. But there are quite a lot of providers to choose from so it doesn't matter much

**Comment by Doctor2023** [comment]
> Yes, Netfilm will have some movies and series that can't be scrape so display Not found sources. But there are quite a lot of providers to choose from so it doesn't matter much

![IMG_0696](https://github.com/lamhoang1256/netfilm/assets/129991276/77261a98-f039-4904-b262-5be348f55ac9)

I get this message also in the movies and series error message

**Comment by lamhoang1256** [comment]
Because of many reasons to get the movie failed: movie not found, site banned, host check ip, cors, ... -> not return data -> movie not found -> 404
