### ISSUE TITLE
sources add providers

### ISSUE THREAD

**Issue by Doctor2023** [lamhoang1256/netfilm#35]
![IMG_0704](https://github.com/lamhoang1256/netfilm/assets/129991276/ee824c51-d34c-463b-94da-653e54810464)

hello I get that message when playing a movies and series

**Comment by Doctor2023** [comment]
add more providers please it would be an excellent idea for the page and app of the netfilm page

**Comment by lamhoang1256** [comment]
Sure bro, i will add when i have time. And do you know any good sources?

**Comment by Doctor2023** [comment]
> Sure bro, i will add when i have time. And do you know any good sources?

https://kimcartoon.li/
https://kisscartoon.sh/
https://www.wco.tv/
https://dramacool.hr/
https://kissasian.mx/
https://www.goojara.to/
https://kissmovies.pro/
https://s.ennovelas.net/
https://ennovelas.online/
https://gitdab.com/recloudstream/cloudstream-extensions
https://gitdab.com/recloudstream/cloudstream-extensions-multilingual
https://recloudstream.github.io/csdocs/recsrc/ extensions cloudstream

**Comment by lamhoang1256** [comment]
Ok thank you very much

**Comment by Doctor2023** [comment]
> Ok thank you very much

When are you going to see more providers for the netflim page and improvements and source changes, there are some pages and cloudstream sources to see if they can add more providers, it would be excellent, more content on movies and series and anime and aniyomi providers

**Comment by lamhoang1256** [comment]
I have a plan to add and optimize many features for netfilm but I don't have time yet. I will try to finish it as soon as possible

**Comment by Doctor2023** [comment]
You will see improvements and changes for netfilm for this year 2023  I m just asking just to know and new providers for netfilm.app

**Comment by lamhoang1256** [comment]
There will be a major update for netfilm in the next 1-2 weeks. And Netfilm will be many providers and many great things in this update 😆

**Comment by Doctor2023** [comment]
> There will be a major update for netfilm in the next 1-2 weeks. And Netfilm will be many providers and many great things in this update 😆

ok friends thanks you let s hope it comes out soon

**Comment by Doctor2023** [comment]
> There will be a major update for netfilm in the next 1-2 weeks. And Netfilm will be many providers and many great things in this update 😆

ok friend I understand thanks for your great work

**Comment by Doctor2023** [comment]
![IMG_0752](https://github.com/lamhoang1256/netfilm/assets/129991276/06fef2ee-7715-49db-9ebf-f9fe58567952)

Some movies are not in English and Spanish, they are in Russian, German, and some providers in English and Spanish are not in English and Spanish the English providers do not work well netfilm.app page

**Comment by Doctor2023** [comment]
![IMG_0754](https://github.com/lamhoang1256/netfilm/assets/129991276/3969b405-9906-4f8e-9e76-e26718f6bae3)

I get this error in the providers

**Comment by lamhoang1256** [comment]
Try clear localStorage bro

**Comment by Doctor2023** [comment]
> ![IMG_0752](https://user-images.githubusercontent.com/129991276/270894473-06fef2ee-7715-49db-9ebf-f9fe58567952.jpeg)
> 
> Hello friend Some movies series are not in English and Spanish they are in Russian, German, and some providers in English and Spanish do not have English and Spanish language providers The English providers do not work well to change the language in the English and Spanish providers and subtitles page netfilm.app


Some English and Spanish providers do not work, subtitles and languages are only in Russian and in Alenan the series and movies I want to change to English and Spanish I cannot in some English language providers

**Comment by Doctor2023** [comment]
![IMG_0755](https://github.com/lamhoang1256/netfilm/assets/129991276/5bbda8a1-e129-4f6a-a553-66bbd45e0e3e)

I get this in red in some providers in English

**Comment by Doctor2023** [comment]
> Try clear localStorage bro

Ok friend

**Comment by lamhoang1256** [comment]
> ![IMG_0755](https://user-images.githubusercontent.com/129991276/271179998-5bbda8a1-e129-4f6a-a553-66bbd45e0e3e.jpeg)
> 
> I get this in red in some providers in English

If a provider has an error, it means that provider does not have the movie you are looking for

**Comment by Doctor2023** [comment]
hello friend You will see more changes and improvements on the netfilm.app page

changes, improvements with languages and subtitles and you will see more providers for the netfilm.app page in some providers you cannot change the language and put subtitles movies series anime

**Comment by Doctor2023** [comment]
> hello friend You will see more changes and improvements on the netfilm.app page
> 
> changes, improvements with languages and subtitles and you will see more providers for the netfilm.app page in some providers you cannot change the language and put subtitles in movies series anime

Hello friend

**Comment by Gareryer** [comment]
I want to share a script with you 
This [SEEZ](https://seez.su/)
