### ISSUE TITLE
Fix pause video media player when input space at SearchBox

### ISSUE THREAD

**Issue by shenlong616** [lamhoang1256/netfilm#5]
![net-film vercel app_watch_0_7259](https://user-images.githubusercontent.com/15698245/211251279-68ac240f-25eb-47ed-9327-f8fefcf8e200.png)

- Khi gõ khoảng trắng trong khung `search` thì `pause()` luôn cả video anh ạ!

**Comment by lamhoang1256** [comment]
@shenlong616 Cảm ơn bác nhé, e mới fix xong rồi, bác rảnh thì có thể kiểm tra lại thử giúp e 😊

[fix-error-search-box.webm](https://user-images.githubusercontent.com/61537853/211494134-6ffec31c-37a3-46ed-9feb-d0344dd8eec5.webm)

**Comment by shenlong616** [comment]
@lamhoang1256 chuẩn r ạ 👍
