### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Convitt** [lamhoang1256/netfilm#7]
Im getting this error 
![image](https://user-images.githubusercontent.com/122373050/214505194-89254f84-0afd-435d-880e-73a1b60053ae.png)

**Comment by lamhoang1256** [comment]
@Convitt Hey bro, have you added firebase config at .env ?

**Comment by lamhoang1256** [comment]
@Convitt  If you run the project at localhost, please create 1 .env file at the same level as .env.example and add firebase configuration at .env

**Comment by lamhoang1256** [comment]
@Convitt  Please let me know if there are still errors bro ✌️

**Comment by gabinfinity** [comment]
hi, im convitt, i forgot my password XD, its working now. Can you help me? Im trying to change AUTO SUBS to PORTUGUESE, im brazilian and i speak portuguese and im trying to change my homepage to america region, can you help me?
![image](https://user-images.githubusercontent.com/59806981/214527175-5ec291dd-cd33-4961-b229-702b45cb8ef3.png)
