### ISSUE TITLE
Portuguese auto subs and american region

### ISSUE THREAD

**Issue by gabinfinity** [lamhoang1256/netfilm#8]
Can you help me? Im trying to change AUTO SUBS to PORTUGUESE, im brazilian and i speak portuguese and im trying to change my homepage to america region, can you help me?
![214527175-5ec291dd-cd33-4961-b229-702b45cb8ef3](https://user-images.githubusercontent.com/59806981/214529551-ad4a74c5-a917-46b1-a367-5a0cbdfb868b.png)

**Comment by gabinfinity** [comment]
Is it possible to add more subtitles API?

**Comment by lamhoang1256** [comment]
@gabinfinity, I think you want a button that when click will automatically switch the language from English to Portuguese ? Example:
```
News -> Notícias
History -> História
Discovery -> Descoberta
To explore ->Explorar
```
Is that what you mean?

**Comment by gabinfinity** [comment]
It's not like that. In LokLok you can change the region of the API and with that it will list the contents in that region. For example, the America region is 61.


![image](https://user-images.githubusercontent.com/59806981/214547737-037b8deb-e43f-47d7-986c-2986fcddef58.png)

**Comment by lamhoang1256** [comment]
@gabinfinity, Sorry bro i still don't understand the question. Do you mean you want to search movies by region ?

![image](https://user-images.githubusercontent.com/61537853/214548615-52ff6106-56b3-45c9-a53f-bab2e16c0142.png)

Or can change the movie source region ?

![language2](https://user-images.githubusercontent.com/61537853/214549315-acb35b80-2af5-4cf0-84f7-507a261f11d5.png)

**Comment by gabinfinity** [comment]
i mean homepage/index, is showing content from asia, is it possible to change the region to America?

![image](https://user-images.githubusercontent.com/59806981/214549755-436f6fde-359f-4f92-ac35-9bdec6591b27.png)

**Comment by lamhoang1256** [comment]
@gabinfinity ah ok i understood the question please wait i try to find the solution

**Comment by lamhoang1256** [comment]
@gabinfinity hey bro you can click change language at Loklok web to português and take a picture of me to see if the loklok homepage has changed
![image](https://user-images.githubusercontent.com/61537853/214551562-dfcd0026-5781-4913-85b1-e0eb4dfec358.png)

**I tried and still no change**

![test2](https://user-images.githubusercontent.com/61537853/214552028-085674dc-b685-41d9-897c-71b60dbf434d.png)

**Comment by gabinfinity** [comment]
![image](https://user-images.githubusercontent.com/59806981/214552561-ef3531dc-0a22-409a-8eff-0f6c15e1e73f.png)
Sure. When I change my language to Portuguese, the content disappears and only the slide remains

**Comment by lamhoang1256** [comment]
@gabinfinity, I think the movie source works fine only in Asia server, when i try to change the server location it doesn't work

![result](https://user-images.githubusercontent.com/61537853/214554778-717dd54b-25c3-47ec-bb66-e5b6b167b0b7.png)

**Comment by gabinfinity** [comment]
Maybe the solution will be change the content in index

**Comment by lamhoang1256** [comment]
@gabinfinity  I think currently one way is to use api explore on the home page

![solution](https://user-images.githubusercontent.com/61537853/214556428-7215be33-000d-49fc-a58d-ba611517963c.png)

**Comment by gabinfinity** [comment]
Can you help me with this?

**Comment by lamhoang1256** [comment]
@gabinfinity  I will @tag you if done

**Comment by gabinfinity** [comment]
Thank you a lot bro. 
I would also like to invite you to this repository (https://github.com/movie-web/movie-web/tree/v3). It's focused on series and movies and a while ago they also tried to add LokLok as a media provider. It would be awesome to have your api along with the other media providers. It would be infinite content.

**Comment by Adhaaz** [comment]
@lamhoang1256 The Sydney Region is actually still less effective because access to Indonesian Film Region content is still hidden by the Loklok Server, but I get a way to overcome it by using the exact same VPN with the Region Function, so that can open access to Indonesian Film Content sir, maybe there is another way sir to open access to Indonesian Film content hidden by the Loklok Server besides using a VPN?

**Comment by gabinfinity** [comment]
LokLok block content based on location?

**Comment by lamhoang1256** [comment]
@gabinfinity  hey bro if you like the homepage look like below, please copy full code to **pages/index.tsx**

![homepage-result](https://user-images.githubusercontent.com/61537853/214561533-6d8d41d5-09b7-40d5-b0a9-f258cf412053.png)

```
import axiosClient from "configs/axiosClient";
import { REVALIDATE_TIME } from "constants/global";
import LayoutPrimary from "layouts/LayoutPrimary";
import CheckInView from "modules/CheckInView";
import HomeBanner from "modules/HomeBanner";
import MovieCard from "modules/MovieCard";
import MovieList from "modules/MovieList";
import { MovieListSkeleton } from "modules/MovieSkeleton";
import { GetStaticProps } from "next";
import queryString from "query-string";
import { useCallback } from "react";
import useSWRInfinite from "swr/infinite";
import { IBanner, ICategoryResult, IHomeSection } from "types";

interface HomePageProps {
  banners: IBanner[];
}

const HomePage = ({ banners }: HomePageProps) => {
  const getApiUrl = (index: number, prevData: ICategoryResult[] | null) => {
    const isEmptyData = prevData?.length === 0;
    if (isEmptyData) return null;
    const sort = prevData?.[prevData.length - 1]?.sort || "";
    const apiURL = `/api/category?${queryString.stringify({ area: "61", size: 12, sort })}`;
    return apiURL;
  };
  const {
    data: movies = [],
    setSize,
    error
  } = useSWRInfinite(
    getApiUrl,
    async (apiURL: string) => {
      const { data } = await axiosClient.get(apiURL);
      return data;
    },
    { revalidateFirstPage: false, fallbackData: [] }
  );
  const isReachingEnd = movies?.[movies.length - 1]?.length === 0;
  const hasNextPage = movies && !error && !isReachingEnd;
  const handleLoadMore = useCallback(() => {
    setSize((prev) => prev + 1);
  }, [setSize]);
  return (
    <LayoutPrimary>
      <div className="container">
        <HomeBanner banners={banners} />
        <div style={{ marginTop: "40px" }}>
          {(movies.length as number) > 0 ? (
            <MovieList>
              {movies.flat().map((result: ICategoryResult) => (
                <MovieCard
                  key={result.id}
                  id={result.id}
                  title={result.name}
                  domainType={result.domainType}
                  poster={result.coverVerticalUrl}
                />
              ))}
            </MovieList>
          ) : (
            <MovieListSkeleton count={12} />
          )}
          {hasNextPage && (
            <CheckInView onInView={handleLoadMore}>
              <MovieListSkeleton />
            </CheckInView>
          )}
        </div>
      </div>
    </LayoutPrimary>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  try {
    const { data: banners } = await axiosClient.get(`/api/banner`);
    return {
      props: { banners },
      revalidate: REVALIDATE_TIME.success
    };
  } catch (error) {
    return {
      props: { banners: [] },
      revalidate: REVALIDATE_TIME.fail
    };
  }
};

export default HomePage;
```

**Comment by gabinfinity** [comment]
Perfect bro, is it possible remove the slide?

**Comment by gabinfinity** [comment]
I got it 
![image](https://user-images.githubusercontent.com/59806981/214564318-eaa21c65-385a-4f9b-b40a-0bb3d449b5af.png)

but is a little slow

This is my code

`import axiosClient from "configs/axiosClient";
import { REVALIDATE_TIME } from "constants/global";
import LayoutPrimary from "layouts/LayoutPrimary";
import CheckInView from "modules/CheckInView";
import HomeBanner from "modules/HomeBanner";
import MovieCard from "modules/MovieCard";
import MovieList from "modules/MovieList";
import { MovieListSkeleton } from "modules/MovieSkeleton";
import { GetStaticProps } from "next";
import queryString from "query-string";
import { useCallback } from "react";
import useSWRInfinite from "swr/infinite";
import { IBanner, ICategoryResult, IHomeSection } from "types";

interface HomePageProps {
  banners: IBanner[];
}

const HomePage = ({ banners }: HomePageProps) => {
  const getApiUrl = (index: number, prevData: ICategoryResult[] | null) => {
    const isEmptyData = prevData?.length === 0;
    if (isEmptyData) return null;
    const sort = prevData?.[prevData.length - 1]?.sort || "";
    const apiURL = `/api/category?${queryString.stringify({ area: "61", size: 12, sort })}`;
    return apiURL;
  };
  const {
    data: movies = [],
    setSize,
    error
  } = useSWRInfinite(
    getApiUrl,
    async (apiURL: string) => {
      const { data } = await axiosClient.get(apiURL);
      return data;
    },
    { revalidateFirstPage: false, fallbackData: [] }
  );
  const isReachingEnd = movies?.[movies.length - 1]?.length === 0;
  const hasNextPage = movies && !error && !isReachingEnd;
  const handleLoadMore = useCallback(() => {
    setSize((prev) => prev + 1);
  }, [setSize]);
  return (
    <LayoutPrimary>
      <div className="container">
        <div style={{ marginTop: "40px" }}>
          {(movies.length as number) > 0 ? (
            <MovieList>
              {movies.flat().map((result: ICategoryResult) => (
                <MovieCard
                  key={result.id}
                  id={result.id}
                  title={result.name}
                  domainType={result.domainType}
                  poster={result.coverVerticalUrl}
                />
              ))}
            </MovieList>
          ) : (
            <MovieListSkeleton count={12} />
          )}
          {hasNextPage && (
            <CheckInView onInView={handleLoadMore}>
              <MovieListSkeleton />
            </CheckInView>
          )}
        </div>
      </div>
    </LayoutPrimary>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  try {
    const { data: banners } = await axiosClient.get(`/api/banner`);
    return {
      props: { banners },
      revalidate: REVALIDATE_TIME.success
    };
  } catch (error) {
    return {
      props: { banners: [] },
      revalidate: REVALIDATE_TIME.fail
    };
  }
};

export default HomePage;`

**Comment by gabinfinity** [comment]
Is it possible to display only movies and series on the website and in the search that have subtitles in Portuguese?

**Comment by lamhoang1256** [comment]
@gabinfinity if you don't use slide copy the code below it will be a bit faster

```
import axiosClient from "configs/axiosClient";
import LayoutPrimary from "layouts/LayoutPrimary";
import CheckInView from "modules/CheckInView";
import MovieCard from "modules/MovieCard";
import MovieList from "modules/MovieList";
import { MovieListSkeleton } from "modules/MovieSkeleton";
import queryString from "query-string";
import { useCallback } from "react";
import useSWRInfinite from "swr/infinite";
import { ICategoryResult } from "types";

const HomePage = () => {
  const getApiUrl = (index: number, prevData: ICategoryResult[] | null) => {
    const isEmptyData = prevData?.length === 0;
    if (isEmptyData) return null;
    const sort = prevData?.[prevData.length - 1]?.sort || "";
    const apiURL = `/api/category?${queryString.stringify({ area: "", size: 12, sort })}`;
    return apiURL;
  };
  const {
    data: movies = [],
    setSize,
    error
  } = useSWRInfinite(
    getApiUrl,
    async (apiURL: string) => {
      const { data } = await axiosClient.get(apiURL);
      return data;
    },
    { revalidateFirstPage: false, fallbackData: [] }
  );
  const isReachingEnd = movies?.[movies.length - 1]?.length === 0;
  const hasNextPage = movies && !error && !isReachingEnd;
  const handleLoadMore = useCallback(() => {
    setSize((prev) => prev + 1);
  }, [setSize]);
  return (
    <LayoutPrimary>
      <div className="container">
        <div style={{ marginTop: "40px" }}>
          {(movies.length as number) > 0 ? (
            <MovieList>
              {movies.flat().map((result: ICategoryResult) => (
                <MovieCard
                  key={result.id}
                  id={result.id}
                  title={result.name}
                  domainType={result.domainType}
                  poster={result.coverVerticalUrl}
                />
              ))}
            </MovieList>
          ) : (
            <MovieListSkeleton count={12} />
          )}
          {hasNextPage && (
            <CheckInView onInView={handleLoadMore}>
              <MovieListSkeleton />
            </CheckInView>
          )}
        </div>
      </div>
    </LayoutPrimary>
  );
};

export default HomePage;
```

**Comment by lamhoang1256** [comment]
@gabinfinity  As you can see Loklok only supports Asian countries well. Loklok only has movies from Asia with Portuguese subtitles but no movies made in Portugal

![image](https://user-images.githubusercontent.com/61537853/214568872-d4fc0120-5218-4301-b547-a06593e9559a.png)

**Comment by Adhaaz** [comment]
@lamhoang1256 Sir, Will the Watch Together feature be added? 🫢

**Comment by gabinfinity** [comment]
Just a suggestion and I don't know if it's possible. It would add more subtitle api. Sometimes there's no subtitles in Portuguese on this one.
The more Subtitles you have on the site, the more people will visit the site. Multiple apis together can generate multiple subtitles.

https://github.com/morpheus65535/bazarr#supported-subtitles-providers
https://gestdown.info/
https://yifysubtitles.org/

**Comment by gabinfinity** [comment]
![image](https://user-images.githubusercontent.com/59806981/214578672-64733cab-1e51-42c3-bd41-5638c58de8da.png)
there is a lot providers, but SuperStream is the best, with LokLok together, nobody can stop us

**Comment by gabinfinity** [comment]
By the way, I'll keep dreaming about LekoLeko together with the movie-web repository. There are several providers, having LekoLeko together means a lot more movies and series.

**Comment by lamhoang1256** [comment]
@gabinfinity I really like your idea and there are so many features i will add to this project.
Currently I have an idea to create new subtitles from Loklok's existing subtitles. For example, with 1 English subtitle can create many new subtitles like French, Portuguese,...

**Comment by gabinfinity** [comment]
"Currently I have an idea to create new subtitles from Loklok's existing subtitles. For example, with 1 English subtitle can create many new subtitles like French, Portuguese,..." This is amazing! Auto-translate would be perfect bro. There are English subtitles for all titles. Translating from English to Portuguese would be perfect

**Comment by gabinfinity** [comment]
![image](https://user-images.githubusercontent.com/59806981/214695956-a8b9c4fd-b6b2-493f-858d-0854bdf36589.png)
These two languages ​​are found in all movies and series, it would be good to use them for translation as well.

**Comment by gabinfinity** [comment]
Since there are subtitles in English for all movies and series, wouldn't it be possible to use subtitles in English and translate automatically into another language?

**Comment by lamhoang1256** [comment]
@gabinfinity maybe the new subtitles will be translated but I think the new subtitles won't be 100% accurate. I will think about how to do this feature

**Comment by gabinfinity** [comment]
Maybe using a google api translator or some api with translate srt files
