### ISSUE TITLE
New feature discussion

### ISSUE THREAD

**Issue by lamhoang1256** [lamhoang1256/netfilm#9]
@Adhaaz I can do Watch Together feature but it will can lag and not as optimized as Loklok. Do you want to use ?

**Comment by Adhaaz** [comment]
Yeah sir, just do it..

**Comment by lamhoang1256** [comment]
@Adhaaz Ok, so how many people are using your website so I can calculate the solution ?

**Comment by Adhaaz** [comment]
For now there are 66 people who have signed up

**Comment by lamhoang1256** [comment]
@Adhaaz ok, bro i will think how to do if done or have problem discuss i will @tag you

**Comment by Adhaaz** [comment]
Okay sir, I'll be waiting for this special feature 🫢

**Comment by lamhoang1256** [comment]
@Adhaaz, Hey bro, I just finished simple watch together

## Preview

https://user-images.githubusercontent.com/61537853/215061233-afada50e-6d86-48e9-ab62-f2c2d804eb24.mp4

## Features

- Add new room together (will delete after 5 hours create)
- Watch videos in realtime sync with the host's media player
- Chat message realtime in room

**Comment by lamhoang1256** [comment]
@Adhaaz, There are many ideas I would love to add to this feature but technology is limited and I don't have much time. Please understand for me 😅

**Comment by Adhaaz** [comment]
> @Adhaaz, Ada banyak ide yang ingin saya tambahkan ke fitur ini tetapi teknologi terbatas dan saya tidak punya banyak waktu. Tolong mengerti untuk saya😅

Okay sir, Thank you.. Your project is amazing sir 🙏🫶

**Comment by Adhaaz** [comment]
@lamhoang1256 Sir, add Downloader m3u8 to mp4 feature using this sir https://github.com/napthedev/m3u8-to-mp4 🙏

**Comment by lamhoang1256** [comment]
@Adhaaz , I tried this feature for a long time but got error

![image](https://user-images.githubusercontent.com/61537853/215508647-6e51ef2e-8a6f-4c9e-8946-ac6d460078ab.png)

**Comment by lamhoang1256** [comment]
@Adhaaz The reason is that when downloading m3u8, you have to add the following code to next.config.js but it will cause conflicts with loklok api

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  swcMinify: true,
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          { key: "Cross-Origin-Embedder-Policy", value: "require-corp" },
          { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
        ],
      },
    ];
  },
};

module.exports = nextConfig;
```

**Comment by lamhoang1256** [comment]
@Adhaaz You can refer this feature at 2 old commits here:

https://github.com/lamhoang1256/netfilm/commit/4918f808e6f921bf242255d79df12db993bc6c96
https://github.com/lamhoang1256/netfilm/commit/eff6ebb46c4b8aea190801abbd69e85fd1b9bd81

**Comment by lamhoang1256** [comment]
@Adhaaz You can create a button at position you want in watch page, click on it and call api/download?url=linkm3u8

**Comment by lamhoang1256** [comment]
You can refer to project napthedev

**Comment by lamhoang1256** [comment]
@Adhaaz Please check here

https://github.com/DuCanhGH/filmhot/blob/main/src/components/WatchView/index.tsx
https://github.com/DuCanhGH/filmhot/blob/main/src/components/WatchView/Download.tsx

**Comment by Adhaaz** [comment]
> @Adhaaz Please check here
> 
> https://github.com/DuCanhGH/filmhot/blob/main/src/components/WatchView/index.tsx https://github.com/DuCanhGH/filmhot/blob/main/src/components/WatchView/Download.tsx

Do you have to use all of this code or your old code, sir? The problem is I've already used the Download Code from u

**Comment by lamhoang1256** [comment]
@Adhaaz I think you should try the code I sent you instead of mine

**Comment by Adhaaz** [comment]
> @Adhaaz I think you should try the code I sent you instead of mine

Sir, how do
![IMG_20230206_111957](https://user-images.githubusercontent.com/75169859/216883143-8372cbf2-8b4b-4172-87ed-62dff3be8545.jpg)
 see the content of this movie? In Loklok, this content is seen, but in Netfilm it is not detected! Is there a way to view this content on Netfilm

**Comment by lamhoang1256** [comment]
@Adhaaz You try using a VPN to switch to an indonesia server and then go to Netflim to find it again

**Comment by Adhaaz** [comment]
> @Adhaaz You try using a VPN to switch to an indonesia server and then go to Netflim to find it again

@lamhoang1256 Still not detected sir 😀 Any other way?

**Comment by Adhaaz** [comment]
![Screenshot_2023-02-14-21-10-55-27_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/75169859/218763288-151ede71-edf6-4965-b8e9-9e54f5513179.jpg)

Sir @lamhoang1256, which section should be changed if want to change the appearance of the homepage to be like this?

**Comment by lamhoang1256** [comment]
@Adhaaz [netfilm](https://github.com/lamhoang1256/netfilm)/[src](https://github.com/lamhoang1256/netfilm/tree/main/src)/[modules](https://github.com/lamhoang1256/netfilm/tree/main/src/modules)/HomeSection

**Comment by Adhaaz** [comment]
Sir @lamhoang1256, it looks like u are working on a Video Player Project based on React-tuby, right? 🥳 The features u added into the Video Player Project are very cool sir @lamhoang1256, I like it. I am interested in the Custom Subtitle Feature. When will it be added to Netfilm Project sir @lamhoang1256 ?

**Comment by Adhaaz** [comment]
> @Adhaaz No, It just is a draft I just use for test. And that project I'm paid to work on, I won't be allowed to use public it if my customer not allow

Okay, sir @lamhoang1256, I get it 👌 I think that project will be added to the netfilm project 🫢

**Comment by Adhaaz** [comment]
Sir @lamhoang1256 , Please update this Netfilm open source, change the Api to FlixHQ because Lok2 API is impossible to use I guess 😀
